# Generated by Django 4.2.11 on 2024-04-02 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('prompt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OpenAIChat',
            new_name='OpenAIStory',
        ),
    ]
